language: node_js
node_js:
  - 6
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
addons:
  firefox: "28.0"
script: grunt travis-ci
branches:
  only:
    - gh-pages # Must specify explicitly
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "echo 'Installing SlimerJS'"
  - "wget https://download.slimerjs.org/releases/0.9.1/slimerjs-0.9.1.zip"
  - "unzip slimerjs-0.9.1.zip"
  - "mv slimerjs-0.9.1 ./slimerjs"
  - "echo 'Installing Grunt'"
  - "npm install -g grunt-cli"
